### ISSUE TITLE
Convert to pure JVM lib

### ISSUE THREAD

**Issue by Syex** [ologe/flow-test-observer#1]
Hi,

I found your lib trying to unit test a `Flow` as encountered the same problem you described in your Medium post. I wanted to try it out, however, my lib currently is no Android lib, meaning I can't use your lib.

From a quick look at it I don't see a reason why it should be an Android lib, you're not using anything from Android package.

If you find some time in the future you maybe can try to convert it.

**Comment by ologe** [comment]
Hi @Syex, you're actually right!

I'll convert it asap, thank you for you feedback

**Comment by ologe** [comment]
I just published `1.3.0`. You should be able to use it on jvm :)

**Comment by Syex** [comment]
That was real quick, awesome job :)
