### ISSUE TITLE
Failed to resolve: com.github.ologe:flow-test-observer:1.4.0

### ISSUE THREAD

**Issue by NurseyitTursunkulov** [ologe/flow-test-observer#2]
Your lib is not resolved:

Failed to resolve: com.github.ologe:flow-test-observer:1.4.0
Show in Project Structure dialog
Affected Modules: core

**Comment by ologe** [comment]
Hi @NurseyitTursunkulov, did you added 
```
maven { url 'https://jitpack.io' }
```
to your repository handler?

**Comment by NurseyitTursunkulov** [comment]
yes I did

**Comment by ologe** [comment]
mmm that's strange. can you provide me the gradle code, or maybe the link to the repo so I can understand it better? thanks

**Comment by NurseyitTursunkulov** [comment]
sorry I added this `maven { url 'https://jitpack.io' }` to the wrong place
